#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.data.mongodb.host=127.0.0.1
#spring.data.mongodb.port=27017
#spring:
#  jpa:
#    show-sql: true
spring:
  data:
    mongodb:
      username: root
      password: root
      database: demo
      host: 127.0.0.1
      port: 27017
#      uri: mongodb://localhost:27017/demo


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jackson.serialization.indent_output=true